---
- name: Create system user
  user: 
    name: "{{ username }}"
    password: "{{ password |password_hash('sha512') }}"
    shell: /bin/bash
    group: sudo

- name: Set authorized key defining key options
  authorized_key:
    user: alex
    state: present
    key: "{{ lookup('file', '/home/alex/.ssh/id_rsa.pub') }}"
