---
- name: Generate locale
  locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: Set default locale
  template:
    src: templates/locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
