---
- name: Install setup tools
  apt: name=python-setuptools state=present
  
- name: Install virtualenv
  command: easy_install virtualenv

- name: Install python3
  apt: name=python3 state=present

- name: Install python postgresql lib
  apt: name=libpq-dev state=present

- name: Install gcc
  apt: name=gcc state=present

- name: Install python3-dev
  apt: name=python3-dev state=present
